### PR TITLE
Fix: Crash when creating a new cublet for a single cube

### LINKED ISSUE #148: Crash when creating a new cublet for a single cube
When loading a large dataset (over 1 GB) into COOL that requires a second cublet to be created, the system crashed with the following error:
```java
Exception in thread "main" java.lang.NullPointerException
        at com.nus.cool.core.io.writestore.MetaUserFieldWS.put(MetaUserFieldWS.java:80)
        at com.nus.cool.core.io.writestore.MetaChunkWS.put(MetaChunkWS.java:144)
        at com.nus.cool.core.util.writer.NativeDataWriter.add(NativeDataWriter.java:177)
        at com.nus.cool.loader.DataLoader.load(DataLoader.java:78)
        at com.nus.cool.model.CoolLoader.load(CoolLoader.java:116)
        at com.nus.cool.functionality.CsvLoader.main(CsvLoader.java:48)
```

### PR DESCRIPTION
**Pull request by tinyAdapter**
Resolve #148

### CODE REVIEW

File: cool-core/src/main/java/com/nus/cool/core/util/writer/NativeDataWriter.java [hunk 1]
```diff
@@ -170,7 +180,9 @@ public boolean add(FieldValue[] tuple) throws IOException {
     }
     // start a new chunk
     if (maybeSwitchChunk(curUser)) {
-      maybeSwitchCublet();
+      if (maybeSwitchCublet()) {
```
Comment (hugy718) [inline cool-core/src/main/java/com/nus/cool/core/util/writer/NativeDataWriter.java:183]: It is better to create a new data chunk. Then we can keep the offset field of data chunk immutable and not exposing a setter.

File: cool-core/src/main/java/com/nus/cool/model/CoolModel.java [hunk 2]
```diff
@@ -143,12 +143,20 @@ public synchronized void reload(String cube) throws IOException {
     CubeRS cubeRS = new CubeRS(schema);
 
     File[] cubletFiles = currentVersion.listFiles((file, s) -> s.endsWith(".dz"));
+    Arrays.sort(cubletFiles);
```
Comment (hugy718) [inline cool-core/src/main/java/com/nus/cool/model/CoolModel.java:146]: Not necessary. But ok.

File: cool-core/src/main/java/com/nus/cool/core/io/writestore/DataChunkWS.java
Comment (hugy718) [inline cool-core/src/main/java/com/nus/cool/core/io/writestore/DataChunkWS.java:1]: By creating a new data chunk when we switch cublet we can keep the field final and avoid this setter.

**Review by hugy718 — CHANGES_REQUESTED** [review]

**Review by hugy718 — APPROVED** [review]
